/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        cream: '#F7F1EA',
        blush: '#F7E9E5',
        blushdeep: '#EAD9D3',
        ink: '#24201D',
        rose: '#C2685C',
        'rose-dark': '#A95349',
        'rose-light': '#E5A39A',
        muted: '#7D746E',
        surface: '#FFFDFB',
        line: '#E8DFD8',
        gold: '#B68A56',
        navy: '#17243A',
        'navy-foreground': '#F5F7FA',
        maroon: '#7A2E3D',
        'maroon-light': '#A85564',
        paper: '#FBF8F3',
        wa: '#D84E55',
        card: '#FFFFFF',
        foreground: '#17243A',
        'muted-foreground': '#687386',
        border: '#E2E6EC',
        background: '#F1F4F8',
        primary: '#C2685C',
        'primary-foreground': '#FFFFFF',
        secondary: '#F1F4F5',
        'secondary-foreground': '#17243A',
        destructive: '#B91C1C',
        'destructive-foreground': '#FFFFFF',
        input: '#D8DEE7',
        ring: '#C2685C',
        accent: '#C2685C',
        'accent-foreground': '#FFFFFF',
        popover: '#FFFFFF',
        'popover-foreground': '#17243A',
      },
      fontFamily: {
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Georgia', 'serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Consolas', 'monospace'],
      },
      letterSpacing: {
        widest2: '0.22em',
      },
    },
  },
  plugins: [],
}
